version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_url_shortener
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4bV38FPQwXh6
      POSTGRES_DB: url_shortener_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
